import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { TodoProvider } from "./todoProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <TodoProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <header className="bg-blue-400 text-white font-extrabold text-xl h-15 flex items-center justify-center">
            TODOLIST
          </header>
          <main className="p-4 bg-blue-100 min-h-[calc(100vh-100px)]">
            {children}
          </main>
          <footer className="h-10 flex items-center justify-center bg-blue-300 text-white">
            © 2025 KANG HYE RIN. All rights reserved.
          </footer>
        </body>
      </TodoProvider>
    </html>
  );
}
